### ISSUE TITLE
examples/path_avoi_control.py doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#2]
kbriggs:> python3 examples/path_avoi_control.py 
Traceback (most recent call last):
  File "examples/path_avoi_control.py", line 59, in <module>
    prob.solve(method='dccp')
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 171, in solve
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/dccp-0.1.0-py3.4.egg/dccp/problem.py", line 31, in dccp
    dccp_ini(self, random=(ccp_times>1)) # initialization; random initial value is mandatory if ccp_times>1
  File "/usr/local/lib/python3.4/dist-packages/dccp-0.1.0-py3.4.egg/dccp/problem.py", line 50, in dccp_ini
    dom_constr = self.objective.args[0].domain # domain of the objective function
AttributeError: 'AddExpression' object has no attribute 'domain'

**Comment by SteveDiamond** [comment]
Are you sure you have the latest cvxpy? There was an update a few days ago to make it compatible with dccp.

**Comment by keithbriggs** [comment]
Then I don't. Does this mean that the custom cvxpy is no longer needed?
K

________________________________________

**Comment by SteveDiamond** [comment]
That's right, you don't need the special cvxpy. You can just use the latest
version of normal cvxpy from pip.
