### ISSUE TITLE
/examples/test.py not working IndexError: list index out of range

### ISSUE THREAD

**Issue by zippydooda** [cvxgrp/dccp#28]
I'm new to Python and just following the installation guide and trying this in a Ubuntu VM.
I've installed anaconda 2.7 and trying the test.py in ../dccp/examples. This is the error message below.
Any help is appreciated.

~/dccp/examples$ python test.py 
problem is DCP: False
problem is DCCP: True
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    result = myprob.solve(method = 'dccp', solver = 'SCS', use_indirect = False, warm_start = True)
  File "/home/localadmin/anaconda2/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/localadmin/anaconda2/lib/python2.7/site-packages/dccp/problem.py", line 36, in dccp
    dccp_ini(self, random=(ccp_times>1), **kwargs) # initialization; random initial value is mandatory if ccp_times>1
  File "/home/localadmin/anaconda2/lib/python2.7/site-packages/dccp/problem.py", line 57, in dccp_ini
    for dom in arg.args[l].domain:
IndexError: list index out of range

Regards

Zi

**Comment by zippydooda** [comment]
I'm using the following versions below.  If you know of other versions that are confirmed as working then please let me know so that I can test.
cvxpy 1.0.6

dccp 0.1.6

**Comment by zippydooda** [comment]
Thanks, that works.
