### ISSUE TITLE
The example on the front page doesn't run due to an indexing error

### ISSUE THREAD

**Issue by malayandi** [cvxgrp/dccp#38]
I was trying out the first example provided on the DCCP GitHub page:

```
import cvxpy as cvx
import dccp
x = cvx.Variable(2)
y = cvx.Variable(2)
myprob = cvx.Problem(cvx.Maximize(cvx.norm(x-y,2)), [0<=x, x<=1, 0<=y, y<=1])
print("problem is DCP:", myprob.is_dcp())   # false
print("problem is DCCP:", dccp.is_dccp(myprob))  # true
result = myprob.solve(method = 'dccp')
print("x =", x.value)
print("y =", y.value)
print("cost value =", result[0])

```

I ran into an error running this code:
```
Traceback (most recent call last):
  File "dccp_error.py", line 8, in <module>
    result = myprob.solve(method = 'dccp')
  File "/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/dccp/problem.py", line 40, in dccp
    dccp_ini(self, random=(ccp_times>1), solver = solver, **kwargs) # initialization; random initial value is mandatory if ccp_times>1
  File "/anaconda3/lib/python3.6/site-packages/dccp/problem.py", line 61, in dccp_ini
    for dom in arg.args[l].domain:
IndexError: list index out of range

```

The error seems to be in this block:

```
   for arg in self.constraints:
       for l in range(2):
           for dom in arg.args[l].domain:
               dom_constr.append(dom) # domain on each side of constraints

```
While digging around, I found that arg.args was a list of length 1 and not 2, as the above block seems to require. The comment seems to imply that the code is attempting to add the domain on “each side of the constraints”, but it seems that cvxpy is already parsing it into one side?

It seems to me than simply changing range(2) to range(1) would solve this issue in the source code?

(For context, I am using cvxpy v1.0.6 and dccp v1.0.0, installed via pip.)

**Comment by malayandi** [comment]
I resolved this issue by installing dccp from source and upgrading cvxpy to a later version (v1.0.21).
