### ISSUE TITLE
Failure on small problem

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/dccp#5]
I ran dccp on this problem
```
from cvxpy import *
import dccp

x = Variable()

prob = Problem(Minimize(log(x)), [x**2 >= 5])
prob.solve(method="dccp")
print x.value
```
and I got a weird error message 
```
iteration= 1 cost value =  0.373930353269 tau =  0.005
max slack =  18.0335348159
iteration= 2 cost value = 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cvxpy/problems/problem.py", line 171, in solve
    return func(self, *args, **kwargs)
  File "/Users/stevend2/anaconda/envs/cvxpy/lib/python2.7/site-packages/dccp-0.1.0-py2.7.egg/dccp/problem.py", line 34, in dccp
    result_temp = iter_dccp(self, max_iter, tau, mu, tau_max, solver)
  File "/Users/stevend2/anaconda/envs/cvxpy/lib/python2.7/site-packages/dccp-0.1.0-py2.7.egg/dccp/problem.py", line 373, in iter_dccp
    print "iteration=",it, "cost value = ", prob_new.solve(), "tau = ", tau
  File "cvxpy/problems/problem.py", line 173, in solve
    return self._solve(*args, **kwargs)
  File "cvxpy/problems/problem.py", line 284, in _solve
    self._update_problem_state(results_dict, sym_data, solver)
  File "cvxpy/problems/problem.py", line 392, in _update_problem_state
    self._handle_no_solution(results_dict[s.STATUS])
  File "cvxpy/problems/problem.py", line 438, in _handle_no_solution
    constr.save_value(None)
AttributeError: 'index' object has no attribute 'save_value'
```
It's non-deterministic (probably due to the randomized initialization).

**Comment by xinyueshen** [comment]
A bug is fixed, and now it should work. Please try the following

> prob.solve(method="dccp", solver = 'SCS', tau = 1)

**Comment by SteveDiamond** [comment]
Great! It works now. Thanks!
