### ISSUE TITLE
 circle_packing.py doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#6]
kbriggs:~> sudo pip install --upgrade cvxpy
kbriggs:~> sudo pip install dccp

kbriggs:~/python> python circle_packing.py
Traceback (most recent call last):
  File "circle_packing.py", line 16, in <module>
    prob.solve(method = 'dccp', ccp_times = 3)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy/problems/problem.py", line 171, in solve
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dccp/dccp_problem.py", line 25, in dccp
    result = iter_dccp(self, max_iter, tau, mu, tau_max, solver)
  File "/usr/local/lib/python2.7/dist-packages/dccp/dccp_problem.py", line 160, in iter_dccp
    temp = convexify_constr(arg)
  File "/usr/local/lib/python2.7/dist-packages/dccp/convexify_constr.py", line 47, in convexify_constr
    lin = linearize(self.args[1])
  File "/usr/local/lib/python2.7/dist-packages/dccp/linearize.py", line 41, in linearize
    for key in expr.gradient:
AttributeError: 'pnorm' object has no attribute 'gradient'

**Comment by SteveDiamond** [comment]
I guess we didn't update PyPi. I pushed the latest version to PyPi, so ``pip install --upgrade dccp`` should work now.

**Comment by keithbriggs** [comment]
Thanks very much – it works now!

BTW, what is the python3 status of these new codes?

Keith

**Comment by keithbriggs** [comment]
I tried 100 circles and it quickly used up all my 8Gb of RAM.   Why should this algorith be memory-hungry?

**Comment by SteveDiamond** [comment]
They are supposed to be python 3 compatible, but I haven't tested them yet.

It probably is using so much memory because there are n^2 constraints,
where n is the number of circles. I'll look into it more deeply too.

**Comment by keithbriggs** [comment]
This example contains “print ...” statements.

Keith
