### ISSUE TITLE
Difference of valid expressions is not a valid expression

### ISSUE THREAD

**Issue by orenbenkiki** [cvxgrp/dccp#73]
I understand that subtracting expressions isn't DCP but it seems like it should be a valid DCCP; however, this seems not to be the case. Here is a simple example:

```python
import cvxpy
import dccp
import numpy

# The real data is much larger, of course.
goal = numpy.array([1.0, 1.0, 1.0])
basis = numpy.array([ [1.0, 0.0, 1.0 ]
                    , [0.0, 1.0, 1.0 ] ])

variables = cvxpy.Variable(2, nonneg=True)
constraints = [cvxpy.sum(variables) == 1]

distance_objective = cvxpy.norm(goal - variables @ basis, 2)
distance_problem = cvxpy.Problem(cvxpy.Minimize(distance_objective), constraints)
print(f'distance is dcp: {distance_problem.is_dcp()}')
print(f'distance is dccp: {dccp.is_dccp(distance_problem)}')  # True, is solved.
distance_result = distance_problem.solve(method='dccp')
print(distance_result)

sparsity_objective = cvxpy.norm(variables, 2)
sparsity_problem = cvxpy.Problem(cvxpy.Maximize(sparsity_objective), constraints)
print(f'sparsity is dcp: {sparsity_problem.is_dcp()}')
print(f'sparsity is dccp: {dccp.is_dccp(sparsity_problem)}')  # True, is solved.
sparsity_result = sparsity_problem.solve(method='dccp')
print(sparsity_result)

sparse_weight = 1.0
total_objective = distance_objective - sparse_weight * sparsity_objective
total_problem = cvxpy.Problem(cvxpy.Minimize(total_objective), constraints)
print(f'total is dcp: {total_problem.is_dcp()}')
print(f'total is dccp: {dccp.is_dccp(total_problem)}')  # False, fails to solve :-(
total_result = total_problem.solve(method='dccp')
print(total_result)
```

The output when running this is:

```
distance is dcp: True
distance is dccp: True
(0.7071067811865508, [array([0.5, 0.5])], 'Converged')
sparsity is dcp: False
sparsity is dccp: True
(0.9999999999474876, [array([1.00000000e+00, 5.25136771e-11])], 'Converged')
total is dcp: False
total is dccp: False
Traceback (most recent call last):
  File "junk.py", line 31, in <module>
    total_result = total_problem.solve(method='dccp')
  File "/home/obk/.local/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 462, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/obk/.local/lib/python3.7/site-packages/dccp/problem.py", line 43, in dccp
    raise Exception("Problem is not DCCP.")
Exception: Problem is not DCCP.
```

Is there some trick that can be used to recast such problems as an acceptable `dccp` problem?

**Comment by xinyueshen** [comment]
Hi @orenbenkiki, to formulate a problem for `dccp`, the objective function and the functions on the left and right hand side of every constraint should be either convex or concave, so in this case the code in the last block can be as follows.
```
sparse_weight = 1.0
t = cvxpy.Variable()
total_objective = distance_objective - sparse_weight * t
constraints.append(t <= sparsity_objective)
total_problem = cvxpy.Problem(cvxpy.Minimize(total_objective), constraints)
print(f'total is dcp: {total_problem.is_dcp()}')
print(f'total is dccp: {dccp.is_dccp(total_problem)}')
total_result = total_problem.solve(method='dccp', tau=1)
print(total_result)
```

**Comment by orenbenkiki** [comment]
Thanks for the prompt reply!

So the trick is to encapsulate the value of the 2nd function in a variable and move it to a constraint, so the goal function itself stays convex?

That does work, representation-wise. That said, for this fake data the solver fails to converge unless I set the sparse_weight extremely low (1e-3 - at which point it might as well be zero). I'll try this with more realistic data and see if it works.

Thanks!

**Comment by orenbenkiki** [comment]
Ugh, apologies. I missed the tau parameter. Yes, it ensures convergence. Serves me right for doing this late at night (Israel time zone). I'll try it tomorrow on real data both with and without the tau and see how it goes.

Many thanks!
