### ISSUE TITLE
Cannot install DCCP

### ISSUE THREAD

**Issue by vnscnap** [cvxgrp/dccp#81]
I tried to install dccp by using pip as well as with downloaded package, but it didn't work for me. Note: CVXPY works for me. Thanks

(base) PS C:\Windows\system32> pip install dccp
Collecting dccp
  Using cached dccp-1.0.4.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2458, in resolve
          return functools.reduce(getattr, self.attrs, module)
      AttributeError: module 'setuptools.dist' has no attribute 'invalid_unless_false'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\vnscn\AppData\Local\Temp\pip-install-fvz047un\dccp_394ce28c015942dba02dfe6908378c0f\setup.py", line 3, in <module>
          setup(
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 446, in __init__
          _Distribution.__init__(
        File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 292, in __init__
          self.finalize_options()
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 822, in finalize_options
          ep(self)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 829, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
          return self.resolve()
        File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2460, in resolve
          raise ImportError(str(exc)) from exc
      ImportError: module 'setuptools.dist' has no attribute 'invalid_unless_false'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xinyueshen** [comment]
Hi @vnscnap, what error did you get when you installed the downloaded package using `python setup.py install`? And what versions of Python and `setuptools` did you use?

**Comment by vnscnap** [comment]
Thanks for your response @xinyueshen When I tried to install with python setup.py install, it showed the setuptools is incompatible. I use Python 3.9, and setuptool 65. I tried to downgrade the setuptools to 58, but it's not successful.
